#!/usr/bin/env bash
# the subdomain www points to your load-balancer IP

function_domain (){
    if [ $# -gt 0 ];
    then
        record=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')
        ip=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')
        echo "The subdomain $2 is a $record record and points to $ip"
    fi
}
if [ $# -eq 2 ];
    then
        function_domain "$1" "$2"
elif [ $# -eq 1 ];
    then
        function_domain "$1" www
        function_domain "$1" lb-01
        function_domain "$1" web-01
        function_domain "$1" web-02
fi 
