#!/usr/bin/env bash
# script that displays

tmp_file="/var/run/my_process.pid"

case $1 in

"start")
    ./manage_my_process &
    echo "$!" > tmp_file
    echo "manage_my_process started"
    ;;
"stop")
    echo "manage_my_process stopped"
    rm $tmp_file
    kill "$(pgrep -f ./manage_my_process)"
    ;;

"restart")
    echo "manage_my_process restarted"
    kill '$(pgrep -f ./manage_my_process)'
    rm $tmp_file
    ./manage_my_process &
    echo "$!" > tmp_file
    ;;

*)
    echo "Usage: manage_my_process {start|stop|restart}"
    ;;
esac
