#!/usr/bin/env bash
# Runs nginx as the user nginx and listening on port 8080
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
